url: https://navygatetechnologies.github.io
baseurl: "" 

# Site settings
title: NavyGate Technologies
email: navygatetechnologies@gmail.com
description: "We specialize in consulting for Computational Fluid Dynamics (CFD), Finite Element Analysis (FEA), and mechanical engineering. Based in the home of IIM Kashipur, we offer high-quality, cost-effective solutions tailored to industry and research needs."


# Team names, titles and social links
people:
- name: Pawan Negi
  pic: 1
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://x.com/Navygatetech 
  - title: instagram
    url: https://instagram.com/navygatetechnologies
  - title: linkedin 
    url: https://linkedin.com/company/navygate-technologies
  - title: github
    url: https://github.com/navygatetechnologies
  - title: youtube
    url: https://www.youtube.com/@NavygateTechnologies

# Postal address (add as many lines as necessary)
address:
  - line: Opp. daffodils Public School 
  - line: Sainik Colony, Kashipur
  - line: Uttarakhand, India, 244713

# Build settings
markdown: kramdown
permalink: pretty